name: tic_tac_socket
description: Server side for tic-tac-toe online
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  socket_io: ^0.9.3
  random_string: ^2.0.1


dev_dependencies:
  pedantic: ^1.9.0
